# application configuration
spring:
    jpa:
        database: default
        generate-ddl: false
        properties.hibernate.default_schema: public
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost/cmi
        username: cmi
        password: cmi
